#!/usr/bin/env python

# s3edgex : a command line to access stores that use the s3 protocol 
#        e.g. AWS S3, NexentaEdge S3, Minio S3 etc 

import platform
import getopt
import sys
import pprint
import os
from os.path import expanduser

import edgex_access

DEFAULT_CONFIG = "/.s3edgex-config"
S3EA_LOG="s3edgex.log"


def config_usage():
    print("s3edgex config")
    print("s3edgex config list")
    print("s3edgex config  show  <store_name>")
    print("s3edgex config  primary <store_name>")
    #print("s3edgex config  primary <store_name> set <ACCESS=...> <SECRET=...>")

def config(edgex_cfg, command, args):
    if len(args) > 0:
        store_name = args[0]
    else:
        store_name = edgex_cfg.getPrimaryService()
    if command == "show":
        pprint.pprint(edgex_cfg.get(store_name))
    elif command in ("-h", "--help"):
        config_usage()
    elif command == "primary":
        if len(args) > 0:
            edgex_cfg.setPrimaryService(args[0], default_config)
        else:
            print(edgex_cfg.getPrimaryService())
    elif command == "list":
        all_cfg = edgex_cfg.getcfg()
        for k,v in all_cfg.items():
            if (k == "PRIMARY") or (k == "DEBUG_LEVEL"):
                print(k + " : " + str(v))
            else:
                print(k)
    else:
        print("Unknown command : " + command)

def process_command(command, args, elog):
    cfg_file = expanduser("~") + DEFAULT_CONFIG 
    edgex_cfg = edgex_access.edgex_config()
    try:
        edgex_cfg.load_file(cfg_file)
    except:
        elog.log_error(" Error loading " + cfg_file  + " config file")
        return
    primary_service = edgex_cfg.getPrimaryService()
    if (command == "list"):
        edgex_store = edgex_access.edgex_store_access(edgex_cfg)
        if not args:
            recursive = False
            edgex_store.list_buckets(recursive)
            return
        if (args[0] == "-r"):
            recursive = True
        else:
            recursive = False
        if args:
            if recursive:
                objname = args[1]
            else:
                objname = args[0]
            objp = objname.split("/")
            bucketName = objp[0]
            objpath = "/".join(objp[1:])
            print(bucketName)
            edgex_store.list(bucketName, objpath, recursive)
    elif (command == "exists"):
        edgex_obj = edgex_access.edgex_obj_access(edgex_cfg)
        f = edgex_obj.exists_obj(args[0])
        print(args[0] + " : " + str(f))
    elif (command == "info"):
        edgex_obj = edgex_access.edgex_obj_access(edgex_cfg)
        f = edgex_obj.info_obj(args[0])
        pprint.pprint(str(f))
    elif (command == "put"):
        edgex_obj = edgex_access.edgex_obj_access(edgex_cfg)
        if (args[0] == "-r"):
            edgex_obj.put_obj_recursive(args[1], dname=args[2])
        else:
            edgex_obj.put_obj(args[0], fileName=args[1])
    elif (command == "get"):
        edgex_obj = edgex_access.edgex_obj_access(edgex_cfg)
        if (args[0] == "-r"):
            edgex_obj.get_obj_recursive(args[1], dname=args[2])
        else:
            edgex_obj.get_obj(args[0], recurse, fileName=args[1])
    elif (command == "del"):
        edgex_obj = edgex_access.edgex_obj_access(edgex_cfg)
        if (args[0] == "-r"):
            edgex_obj.remove_obj_recursive(args[1])
        else:
            edgex_obj.remove_obj(args[0], recurse)
    elif (command == "test"):
        edgex_obj = edgex_access.edgex_obj_access(edgex_cfg)
        if args:
            edgex_obj.test_one_obj(args[0])
        else:
            edgex_obj.test_one_obj("")
    elif (command == "config"):
        if (not args):
            config(edgex_cfg, "show", [])
        else:
            config(edgex_cfg, args[0], args[1:])
    else:
        elog.log_error('CommandError', "Unknown command: " + command)

def system_info(debug_level):
    print("python \t\t: " + platform.python_version() + " " + platform.python_implementation() + " " + str(platform.python_build()))
    print("platform \t: " + platform.node() + " " + platform.system() + " " + platform.machine() + " " + platform.release())
    print("uname \t\t: " + platform.uname().version)
    print("debug_level \t: " + str(debug_level))

def usage():
    print(sys.argv[0] + " --help")
    print(sys.argv[0] + " --system")
    print(sys.argv[0] + " [ --debug <level> ] <command> <objname> <arg>")
    print("Commands:")
    print("\t\tconfig")
    print("\t\tlist")
    print("\t\texists")
    print("\t\tput")
    print("\t\tget")
    print("\t\tdel")
    print("\t\ttest")
    print("Examples:")
    print("\t% " + sys.argv[0] + " [ --debug <level> ] list [ -r ]")
    print("\t% " + sys.argv[0] + " [ --debug <level> ] list [ -r ] <bucketname>")
    print("\t% " + sys.argv[0] + " get <bucketname/filename> <filename>")
    print("\t% " + sys.argv[0] + " get [ -r ] <bucketname/dirname> <dirname>")
    print("\t% " + sys.argv[0] + " put <bucketname/filename> <filename>")
    print("\t% " + sys.argv[0] + " put [ -r ] <bucketname/dirname> <dirname>")
    print("\t% " + sys.argv[0] + " del <bucketname/filename>")
    print("\t% " + sys.argv[0] + " del [ -r ] <bucketname/dirname>")
    print("\t% " + sys.argv[0] + " info <bucketname/filename>")
    print("\t% " + sys.argv[0] + " exists <bucketname/filename>")

def main():
    debug_level = 4
    try:
        opts, remainder = getopt.getopt(sys.argv[1:], "hd:s", ["help", "debug", "system"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for o,a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit(2)
        if o in ("-d", "--debug"):
            debug_level = a
        if o in ("-s", "--system"):
            system_info(debug_level)
            sys.exit(0)
    if (len(remainder) < 1):
        usage()
        sys.exit(2)
 
    elog = edgex_access.edgex_logger(debug_level, S3EA_LOG) 
    elog.log_info(sys.argv[0] + " started")

    command = remainder[0]
    if len(remainder[1:]) >= 1:
        process_command(command, remainder[1:], elog)
    else:
        process_command(command, None, elog)

    elog.log_info(sys.argv[0] + " ended")

if __name__ == '__main__':
    main()
